### ISSUE TITLE
Problem with LeadConvertSettings

### ISSUE THREAD

**Issue by abdullah-tayeh** [gdman/sfdx-destruction#3]
I was trying to remove Conversion mappings for leads, but this doesn't seem to work, I am not entirely sure what the problem is:

```
SFDX destructive changes plugin enabled
Adding manifest/destructiveChangesPre.xml to package
Adding manifest/destructiveChangesPost.xml to package
Job ID | 0Af6700000Oup9MCAR
SOURCE PROGRESS | ████████████████████████████████████████ | 0/0 ComponentsSOURCE PROGRESS | ████████████████████████████████████████ | 1/1 ComponentsSOURCE PROGRESS | ████████████████████████████████████████ | 3/3 Components

=== Component Failures [1]
TYPE     FILE                                                       NAME                    PROBLEM
───────  ─────────────────────────────────────────────────────────  ──────────────────────  ─────────────────────────────────────
Warning  sdx_sourceDeploy_pkg_1619189071471/destructiveChanges.xml  destructiveChanges.xml  No LeadConvertSettings named: * found
```

My destructiveChangesPre.xml contains like this:

```
<types>
        <members>*</members>
        <name>LeadConvertSettings</name>
</types>
```

I was able to retrieve the convertion settings, but I can't seem to delete them.

**Comment by gdman** [comment]
It looks like the plugin is working correctly as the destructive changes files have been added to the deployment so this isn't really an issue for this repository.

That said, I can still give some advice. The issue is with the contents of the destructive changes file. I think it's that you can't have wildcards, you need to specify the exact components that you want to delete. I'm not 100% certain of that, just going off the error message and that I can't think of a case where you'd want to delete everything.

I'm also not sure about the idea of deleting lead convert settings as that's essentially standard metadata with custom mappings added, I'd have thought you'd want to change the contents of the file to remove the mappings you don't want (or remove the mappings in Salesforce and then re-retrieve the file).
